web:
  build: ./build/
  links:
    - db
  ports:
    - "8000:80"
  volumes:
    - .:/var/www/html/
db:
  image: mysql:5.5
  ports:
    - "13306:3306"
  environment:
    MYSQL_RANDOM_ROOT_PASSWORD: true
    MYSQL_USER: isp
    MYSQL_PASSWORD: isp
    MYSQL_DATABASE: isp
