web:
  build: ./build/
  links:
    - database
  ports:
    - "8000:80"
  volumes:
    - .:/var/www/html/
  environment:
    DB_HOST: database
database:
  image: mysql:5.5
  environment:
    MYSQL_RANDOM_ROOT_PASSWORD: true
    MYSQL_USER: isp
    MYSQL_PASSWORD: isp
    MYSQL_DATABASE: isp
